# Generated by Django 4.2.6 on 2023-10-31 15:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0002_alter_news_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ('-id',), 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AddField(
            model_name='news',
            name='dislike',
            field=models.ManyToManyField(blank=True, related_name='news_dislikes', to=settings.AUTH_USER_MODEL, verbose_name='Дизлайк'),
        ),
        migrations.AlterField(
            model_name='news',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='news_likes', to=settings.AUTH_USER_MODEL, verbose_name='Лайки'),
        ),
    ]
